CCDNMessage\MessageBundle\Entity\Registry:
    type: entity
    table: cc_message_registry
    id:
        id:
            type: integer
            generator: { strategy: AUTO }
    fields:
        cachedUnreadMessageCount:
            type: integer
            column: cached_unread_message_count
    manyToOne:
        ownedByUser:
            targetEntity: Symfony\Component\Security\Core\User\UserInterface
            cascade: ["remove"]
            joinColumn:
                name: fk_owned_by_user_id
                referencedColumnName: id
                onDelete: SET NULL
