parameters:

    # Service Parameters defined in app/config.
    ccdn_message_message.component.server.message.class: CCDNMessage\MessageBundle\Component\Server\MessageServer
    ccdn_message_message.component.helper.pagination_config.class: CCDNMessage\MessageBundle\Component\Helper\PaginationConfigHelper
    ccdn_message_message.component.crumb_builder.class: CCDNMessage\MessageBundle\Component\Crumbs\CrumbBuilder
    ccdn_message_message.component.crumb_factory.class: CCDNMessage\MessageBundle\Component\Crumbs\Factory\CrumbFactory
    ccdn_message_message.component.helper.folder.class: CCDNMessage\MessageBundle\Component\Helper\FolderHelper
    ccdn_message_message.component.helper.quota.class:  CCDNMessage\MessageBundle\Component\Helper\QuotaHelper
    ccdn_message_message.component.event_listener.flash.class: CCDNMessage\MessageBundle\Component\Dispatcher\Listener\FlashListener
    ccdn_message_message.component.event_listener.stats.class: CCDNMessage\MessageBundle\Component\Dispatcher\Listener\StatListener

services:

    ccdn_message_message.component.server.message:
        class: %ccdn_message_message.component.server.message.class%
        arguments:
            - @event_dispatcher
            - @ccdn_message_message.model.folder
            - @ccdn_message_message.model.message
            - @ccdn_message_message.model.envelope
            - @ccdn_message_message.model.user
            - @ccdn_message_message.component.helper.quota
            - @ccdn_message_message.component.helper.folder

    ccdn_message_message.component.helper.folder:
        class: %ccdn_message_message.component.helper.folder.class%
        arguments:
            - @ccdn_message_message.model.folder

    ccdn_message_message.component.helper.quota:
        class: %ccdn_message_message.component.helper.quota.class%
        arguments:
            - %ccdn_message_message.quotas.max_messages%

    ccdn_message_message.component.helper.pagination_config:
        class: %ccdn_message_message.component.helper.pagination_config.class%
        arguments:
            - %ccdn_message_message.folder.show.messages_per_page%

    #
    # Dashboard Integrator.
    #
    ccdn_message_message.component.dashboard.integrator:
        class: %ccdn_message_message.component.dashboard.integrator.class%
        tags:
            - { name: ccdn_component_dashboard.integrator }

    ccdn_message_message.component.flood_control:
        class: %ccdn_message_message.component.flood_control.class%
        arguments:
            - @security.context
            - @session
            - %kernel.environment%
            - %ccdn_message_message.message.flood_control.send_limit%
            - %ccdn_message_message.message.flood_control.block_for_minutes%

    #
    # Event Subscribers.
    #
    ccdn_message_message.component.event_listener.flash:
        class: %ccdn_message_message.component.event_listener.flash.class%
        arguments: [@session]
        tags:
            - { name: kernel.event_subscriber }

    ccdn_message_message.component.event_listener.stats:
        class: %ccdn_message_message.component.event_listener.stats.class%
        arguments:
            - @ccdn_message_message.model.folder
            - @ccdn_message_message.model.envelope
            - @ccdn_message_message.model.registry
        tags:
            - { name: kernel.event_subscriber }

    #
    # Crumbs.
    #
    ccdn_message_message.component.crumb_factory:
        class: %ccdn_message_message.component.crumb_factory.class%
        arguments:
            - @translator
            - @router

    ccdn_message_message.component.crumb_builder:
        class: %ccdn_message_message.component.crumb_builder.class%
        arguments:
            - @ccdn_message_message.component.crumb_factory
